name: Deploy cavecreekgoldens.com

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Copy files to AWS server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json"
          target: "/home/ubuntu/apps/nodejs/cavecreekgoldens"

      - name: Restart app with PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/nodejs/cavecreekgoldens
            npm install --omit=dev
            pm2 restart cavecreekgoldens || pm2 start "node_modules/next/dist/bin/next" --name cavecreekgoldens -- start -p 3010
